<?php

// @codingStandardsIgnoreFile

// DO NOT EDIT THIS FILE
// This file is managed by launchpad, and will be regenerated every time you
// start this project.

// Default settings that are needed, but can be overridden in local settings.
$settings['hash_salt'] = "LnfgDsc3WD9F3qNfHK6a95jjJkwzDkh0";
$db_prefix = '';

if (file_exists(DRUPAL_ROOT . '/../etc/drupal/settings_local.php')) {
  include_once DRUPAL_ROOT . '/../etc/drupal/settings_local.php';
}

// Ensure the theme vendor folders are excluded from file scanning.
$settings['file_scan_ignore_directories'] = [
  'node_modules',
  'bower_components',
];

// Ensure there is no base url active, as this breaks the whole traefik logic.
$base_url = NULL;

// Ensure tmp folder is an existing folder, no matter what is configured.
$config['system.file']['path']['temporary'] = '/tmp';

// Set all database settings, except from the $db_prefix, so the db connection 
// is compatible with imported db's that use prefixes.
$db_name = 'woutersfbjjtimer_local';
$db_user = 'woutersfbjjtimer';
$db_pass = 'woutersfbjjtimer_password';
$db_host = 'db.woutersfbjjtimer-docker';
$db_port = '';
$db_driver = 'mysql';

$databases['default']['default'] = [
  'database' => $db_name,
  'username' => $db_user,
  'password' => $db_pass,
  'host' => $db_host,
  'port' => $db_port,
  'driver' => $db_driver,
  'prefix' => $db_prefix,
];

if (PHP_SAPI != 'cli') {
  // As the requests are routed through Traefik (and possibly Varnish), there is
  // a reverse proxy active.
  $settings['reverse_proxy'] = TRUE;

  // As the reverse proxy IP addresses are defined outside of the knowledge of
  // this container, we cannot add fixed IP addresses tot the
  // reverse_proxy_addresses list. So we add the incoming addresses as reverse
  // proxy addresses.
  // DO NOT EVER EVER put this setting on a staging or live environment, as this
  // makes IP address spoofing possible.

  // Parse all forwarded for addresses, and remove the real client ip.
  $proxy_list = array_map('trim', explode(',', $_SERVER['HTTP_X_FORWARDED_FOR']));
  if (($key = array_search($_SERVER['HTTP_X_REAL_IP'], $proxy_list)) !== false) {
    unset($proxy_list[$key]);
  }
  // The remote address can never be the client directly, as Traefik is at least 
  // in between, so add that ip to the proxy list.
  $proxy_list[] = $_SERVER['REMOTE_ADDR'];
  $proxy_list = array_unique($proxy_list);

  $settings['reverse_proxy_addresses'] = $proxy_list;
}

// Add a Launchpad entry to the trusted host patterns info if configured.
if (isset($settings['trusted_host_patterns'])) {
  $pattern = preg_quote(".woutersfbjjtimer.docker.localhost");
  $settings['trusted_host_patterns'][] = '^.*' . $pattern . '$';
}
